### PR TITLE
Several cmake fixes

### PR DESCRIPTION
**Pull request by ChristopherHogan**
* Removed several unnecessary commands
* Fixed linking of tests with `libbasket.so` (no more `LD_PRELOAD`)
* Changed `SERVER_LIST_PATH` in tests (the tests run inside `CMAKE_BINARY_DIR/tests` when `ctest` is used).
* Removed `WILL_FAIL true` property from tests. I verified that both MPICH 3.2.1 and 3.3.1 are ok with this.
@hariharan-devarajan @Keith-Bateman

### CODE REVIEW

**Comment by hariharan-devarajan** [comment]
Why did you remove the copy command of the cmake list? We need to still copy the serverlist file

**Comment by hariharan-devarajan** [comment]
Also, you need the preload property in case we don't do ld_library path. I would recommend to keep it.

**Comment by ChristopherHogan** [comment]
> Why did you remove the copy command of the cmake list? We need to still copy the serverlist file

The `server_list` file gets copied in [tests/CMakeLists.txt:14](https://github.com/hariharan-devarajan/basket/blob/ed714c973b576939aa08b9d0a5e4e30f947ed57d/test/CMakeLists.txt#L14). The code I removed doesn't seem to do anything. It copies the empty string to the `test` directory.

> Also, you need the preload property in case we don't do ld_library path. I would recommend to keep it.

The point of my changes is that you never have to set `LD_LIBRARY_PATH` or `LD_PRELOAD` for the tests to find `libbasket.so`. Simply passing the target `basket` to `target_link_libraries` instead of manually specifiying all the flags means that cmake will use an `RPATH` of `CMAKE_BINARY_DIR` by default. Here's an example link line built with the changes in this PR:

```bash
mpicxx [...] queue_test.cpp.o  -o queue_test -Wl,-rpath,/home/chogan/basket/build ../libbasket.so.1.0.0 -lrpc -lmpi -lpthread -lrt
```

And then, from any directory, the test executable can always find `libbasket.so` without relying on `LD_LIBRARY_PATH` or `LD_PRELOAD`. 

```bash
cd basket/build
ldd test/queue_test
> libbasket.so.1 => /home/chogan/basket/build/libbasket.so.1 (0x00007f1390f1d000)

cd ~
ldd basket/build/test/queue_test
> libbasket.so.1 => /home/chogan/basket/build/libbasket.so.1 (0x00007f1390f1d000)
```

Of course, you still have to use `LD_LIBRARY_PATH` for `libbasket.so` to find `librpc.so`, but if you invoke cmake with `-DCMAKE_BUILD_RPATH=/path/to/librpc.so` then you never need `LD_LIBRARY_PATH` or `LD_PRELOAD` for anything.

**Comment by hariharan-devarajan** [comment]
Agr

> > Why did you remove the copy command of the cmake list? We need to still copy the serverlist file
> 
> The `server_list` file gets copied in [tests/CMakeLists.txt:14](https://github.com/hariharan-devarajan/basket/blob/ed714c973b576939aa08b9d0a5e4e30f947ed57d/test/CMakeLists.txt#L14). The code I removed doesn't seem to do anything. It copies the empty string to the `test` directory.
> 
> > Also, you need the preload property in case we don't do ld_library path. I would recommend to keep it.
> 
> The point of my changes is that you never have to set `LD_LIBRARY_PATH` or `LD_PRELOAD` for the tests to find `libbasket.so`. Simply passing the target `basket` to `target_link_libraries` instead of manually specifiying all the flags means that cmake will use an `RPATH` of `CMAKE_BINARY_DIR` by default. Here's an example link line built with the changes in this PR:
> 
> ```shell
> mpicxx [...] queue_test.cpp.o  -o queue_test -Wl,-rpath,/home/chogan/basket/build ../libbasket.so.1.0.0 -lrpc -lmpi -lpthread -lrt
> ```
> 
> And then, from any directory, the test executable can always find `libbasket.so` without relying on `LD_LIBRARY_PATH` or `LD_PRELOAD`.
> 
> ```shell
> cd basket/build
> ldd test/queue_test
> > libbasket.so.1 => /home/chogan/basket/build/libbasket.so.1 (0x00007f1390f1d000)
> 
> cd ~
> ldd basket/build/test/queue_test
> > libbasket.so.1 => /home/chogan/basket/build/libbasket.so.1 (0x00007f1390f1d000)
> ```
> 
> Of course, you still have to use `LD_LIBRARY_PATH` for `libbasket.so` to find `librpc.so`, but if you invoke cmake with `-DCMAKE_BUILD_RPATH=/path/to/librpc.so` then you never need `LD_LIBRARY_PATH` or `LD_PRELOAD` for anything.

Agreed. But I would still say for now let the ld_preload be there. We can remove it once we test it on Cori.

**Comment by ChristopherHogan** [comment]
Restored `LD_PRELOAD` for tests.

**Pull request merged**
